on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get purge -y containerd*  # Remove conflicting containerd packages
          sudo apt-get install -y docker.io  # Install Docker without conflicts
          sudo systemctl start docker

      # Step 3: Fix Held Packages
      - name: Fix Held Packages
        run: |
          sudo apt-get update
          sudo apt-mark unhold $(sudo apt-mark showhold) || true  # Unhold all held packages
          sudo apt-get -f install -y  # Fix broken dependencies
          sudo apt-get autoremove -y  # Remove unused packages
          sudo apt-get autoclean -y  # Clean old packages

      # Step 4: Pull official Ubuntu Docker Image
      - name: Pull Ubuntu Docker Image
        run: |
          docker pull ubuntu:22.04  # Use Ubuntu 22.04 image

      # Step 5: Install Dependencies inside Docker
      - name: Install Dependencies
        run: |
          docker run --rm \
            -v ${PWD}:/project \
            -w /project \
            ubuntu:22.04 bash -c " \
            # Run as root
            apt-get update && \
            apt-get install -y sudo python3.10 python3.10-venv curl wget unzip && \
            ln -s /usr/bin/python3.10 /usr/bin/python3 && \
            # Install pip using the recommended method
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
            python3 get-pip.py && \
            rm get-pip.py && \
            # Create virtual environment
            python3 -m venv env || { echo 'Error: Failed to create virtual environment!'; exit 1; } && \
            source env/bin/activate || { echo 'Error: Virtual environment activation failed!'; exit 1; } && \
            # Install dependencies
            python -m pip install --upgrade pip setuptools wheel && \
            pip install buildozer cython kivy && \
            # Check if buildozer.spec exists
            if [ ! -f buildozer.spec ]; then \
              echo 'Error: buildozer.spec not found!'; exit 1; \
            fi && \
            # Build APK
            echo 'Building APK...' && \
            buildozer --noinput android debug && \
            # Check if APK is in bin directory
            if [ -d bin ]; then \
              ls -la bin/; \
            else \
              echo 'Error: bin directory not found!'; exit 1; \
            fi"

      # Step 6: Upload APK
      - name: Upload APK
        if: success()  # Run only if previous step succeeds
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
